#!/usr/bin/env python
'''This is a python SQL database''' 

import sqlite3

conn = sqlite3.connect('pso_database')
c = conn.cursor()

# Create three tables UNITS, MATERIALS, MAG
c.execute('''CREATE TABLE IF NOT EXISTS UNITS
            (p_id INTEGER PRIMARY KEY AUTOINCREMENT, units TEXT)''')
c.execute('''CREATE TABLE IF NOT EXISTS MATERIALS
            (p_id INTEGER PRIMARY KEY AUTOINCREMENT, idealNumber INTEGER, material TEXT, givenNumber INTEGER)''')
c.execute('''CREATE TABLE IF NOT EXISTS MAGS
            (p_id INTEGER PRIMARY KEY AUTOINCREMENT, magName TEXT, attributes TEXT, idealNumber INTEGER, photonBlast TEXT)''')

# Insert multiple rows of Data into each table:
Units = [(1, 'GOD ABILITY'),
        (2, 'GOD ABILITY'),
        (3, 'GOD LEGS'),
        (4, 'FREE SLOT')]

c.executemany('INSERT INTO UNITS VALUES (?,?)', Units)

Materials = [(1, 90, 'Power', 0),
            (2, 28, 'Def', 0),
            (3, 0, 'Mind', 0),
            (4, 0, 'Evade', 0),
            (5, 25, 'Luck', 0)]  
c.executemany('INSERT INTO MATERIALS VALUES (?,?,?,?)', Materials)

Mag = [('SATO', 'DEF', 5, 'Estilla'),
        ('SATO', 'POW', 137, 'Milla and Youlla'),
        ('SATO', 'DEX', 58, 'Pilla'),
        ('SATO', 'MST', 0)]

c.executemany('INSERT INTO MAG VALUES (?,?,?,?)', Mag)

conn.commit()
