#!/usr/bin/env python
'''This is a python SQL database'''

import sqlite3

conn = sqlite3.connect('pso_database.db')
c = conn.cursor()

# Create three tables: UNITS, MATERIALS, MAG
c.execute('''CREATE TABLE IF NOT EXISTS Units
            (p_id INTEGER PRIMARY KEY, units TEXT)''')
c.execute('''CREATE TABLE IF NOT EXISTS Materials
            (p_id INTEGER PRIMARY KEY, idealNumber INTEGER, material TEXT, givenNumber INTEGER)''')
c.execute('''CREATE TABLE IF NOT EXISTS Mags
            (p_id INTEGER PRIMARY KEY, magName TEXT, attributes TEXT, idealNumber INTEGER, photonBlast TEXT)''')

# Insert multiple rows of Data into each table:
Units = [(1, 'GOD ABILITY'),
        (2, 'GOD ABILITY'),
        (3, 'GOD LEGS'),
        (4, 'FREE SLOT')]

c.executemany('INSERT INTO UNITS VALUES (?,?)', Units)

Materials = [(1, 90, 'Power', 0),
            (2, 28, 'Def', 0),
            (3, 0, 'Mind', 0),
            (4, 0, 'Evade', 0),
            (5, 25, 'Luck', 0)]
c.executemany('INSERT INTO MATERIALS VALUES (?,?,?,?)', Materials)

Mag = [(1,'SATO', 'DEF', 5, 'Estilla'),
        (2,'SATO', 'POW', 137, 'Milla and Youlla'),
        (3,'SATO', 'DEX', 58, 'Pilla'),
        (4,'SATO', 'MST', 0, 'None')]

c.executemany('INSERT INTO MAGS VALUES (?,?,?,?,?)', Mag)

conn.commit()

conn.close()
