#!/usr/bin/env python
'''Program to interact with PSO_DATABASE'''

import sqlite3

conn = sqlite3.connect('pso_database')
c = conn.cursor()

def print_rows(table):
    for row in c.execute(f'SELECT * FROM {table}'):
        print(row)
    print('\n')

print_rows('MAGS')
print_rows('MATERIALS')
print_rows('UNITS')
